export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT'
export const GET_PRODUCTS_BY_PAGE = 'GET_PRODUCTS_BY_PAGE'
export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_SEARCH = 'GET_SEARCH'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DECREASE_ITEM_IN_CART = 'DECREASE_ITEM_IN_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const REGISTER_ORDER = 'REGISTER_ORDER'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const EMPTY_CART = "EMPTY_CART"
export const TOGGLE_SHOW_MODAL = "TOGGLE_SHOW_MODAL"
export const LOG_IN = "LOG_IN"
export const GET_ME = "GET_ME"
export const GET_ORDER_HISTORY = "GET_ORDER_HISTORY"
export const CHANGE_MODAL = "CHANGE_MODAL"
export const REGISTER_USER = "REGISTER_USER"
export const STORE_USER_INFO = "STORE_USER_INFO"
export const LOG_OUT = "LOG_OUT"
export const TOGGLE_UPDATE_INFO = "TOGGLE_UPDATE_INFO"
export const UPDATE_USER = "UPDATE_USER"



export default {
    GET_ONE_PRODUCT,
    GET_PRODUCTS_BY_PAGE, 
    GET_CATEGORY,
    GET_SEARCH,
    ADD_TO_CART,
    DECREASE_ITEM_IN_CART, 
    REMOVE_FROM_CART, 
    REGISTER_ORDER, 
    CLEAR_ERROR, 
    EMPTY_CART, 
    TOGGLE_SHOW_MODAL, 
    LOG_IN, 
    GET_ME, 
    GET_ORDER_HISTORY,
    CHANGE_MODAL,
    REGISTER_USER,
    STORE_USER_INFO,
    LOG_OUT,
    TOGGLE_UPDATE_INFO,
    UPDATE_USER
}