export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT'
export const GET_PRODUCTS_BY_PAGE = 'GET_PRODUCTS_BY_PAGE'
export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_SEARCH = 'GET_SEARCH'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DECREASE_ITEM_IN_CART = 'DECREASE_ITEM_IN_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export default {
    GET_ONE_PRODUCT,
    GET_PRODUCTS_BY_PAGE, 
    GET_CATEGORY,
    GET_SEARCH,
    ADD_TO_CART,
    DECREASE_ITEM_IN_CART, 
    REMOVE_FROM_CART
}