export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT'
export const GET_PRODUCTS_BY_PAGE = 'GET_PRODUCTS_BY_PAGE'
export const GET_CATEGORY = 'GET_CATEGORY'
export const GET_SEARCH = 'GET_SEARCH'

export default {
    GET_ONE_PRODUCT,
    GET_PRODUCTS_BY_PAGE, 
    GET_CATEGORY,
    GET_SEARCH
}