export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const SAVE_ONE_PRODUCT = 'SAVE_ONE_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DECREASE_ITEM_IN_CART = 'DECREASE_ITEM_IN_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SET_ERROR_ON_PAGE = 'SET_ERROR_ON_PAGE'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const EMPTY_CART = "EMPTY_CART"

export default {
    SAVE_PRODUCTS, 
    SAVE_ONE_PRODUCT,
    ADD_TO_CART,
    DECREASE_ITEM_IN_CART, 
    REMOVE_FROM_CART, 
    SET_ERROR_ON_PAGE, 
    CLEAR_ERROR, 
    EMPTY_CART
}