export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const SAVE_ONE_PRODUCT = 'SAVE_ONE_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DECREASE_ITEM_IN_CART = 'DECREASE_ITEM_IN_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export default {
    SAVE_PRODUCTS, 
    SAVE_ONE_PRODUCT,
    ADD_TO_CART,
    DECREASE_ITEM_IN_CART, 
    REMOVE_FROM_CART
}