export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const SAVE_ONE_PRODUCT = 'SAVE_ONE_PRODUCT'
export const ADD_TO_CART = 'ADD_TO_CART'
export const DECREASE_ITEM_IN_CART = 'DECREASE_ITEM_IN_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const SET_ERROR_ON_PAGE = 'SET_ERROR_ON_PAGE'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const EMPTY_CART = "EMPTY_CART"
export const TOGGLE_SHOW_MODAL = "TOGGLE_SHOW_MODAL"
export const SET_ERROR_ON_MODAL = "SET_ERROR_ON_MODAL"
export const LOG_IN = "LOG_IN"
export const SAVE_ORDER_HISTORY = "SAVE_ORDER_HISTORY"
export const CHANGE_MODAL = "CHANGE_MODAL"
export const STORE_USER_INFO = "STORE_USER_INFO"
export const LOG_IN_LOG_OUT = "LOG_IN_LOG_OUT"
export const DISPOSE_USER = "DISPOSE_USER"
export const TOGGLE_UPDATE_INFO = "TOGGLE_UPDATE_INFO"

export default {
    SAVE_PRODUCTS, 
    SAVE_ONE_PRODUCT,
    ADD_TO_CART,
    DECREASE_ITEM_IN_CART, 
    REMOVE_FROM_CART, 
    SET_ERROR_ON_PAGE, 
    CLEAR_ERROR, 
    EMPTY_CART, 
    TOGGLE_SHOW_MODAL, 
    SET_ERROR_ON_MODAL, 
    LOG_IN, 
    SAVE_ORDER_HISTORY,
    CHANGE_MODAL,
    STORE_USER_INFO,
    LOG_IN_LOG_OUT,
    DISPOSE_USER,
    TOGGLE_UPDATE_INFO
}